version: '3.3'
services:
  db:
    image: postgres:14
    env_file:
      - .env
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "5433:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${POSTGRES_USER} -d ${POSTGRES_DB}"]
      interval: 10s
      timeout: 5s
      retries: 5

  backend:
    build: ./backend
    command: /usr/local/bin/entrypoint.sh sh -c './wait-for-it.sh db && /home/appuser/.local/bin/alembic upgrade head && /home/appuser/.local/bin/uvicorn app.main:app --host 0.0.0.0 --port 8000'
    env_file:
      - .env
    environment:
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_DB=${POSTGRES_DB}
      - ALEMBIC_DATABASE_URL=postgresql://${POSTGRES_USER}:${POSTGRES_PASSWORD}@db:5432/${POSTGRES_DB}
    depends_on:
      - db
    healthcheck:
      test: ["CMD", "python", "-c", "import httpx; exit(1) if httpx.get('http://localhost:8000/api/v1/health').status_code != 200 else exit(0)"]
      interval: 30s
      timeout: 30s
      retries: 3
    ports:
      - "8000:8000"
    volumes:
      - uploaded_files:/app/uploads

  school-portal:
    build: ./frontend/school-portal
    ports:
      - "8082:80"
    depends_on:
      - backend
    healthcheck:
      test: ["CMD", "curl", "--fail", "http://localhost/"]
      interval: 30s
      timeout: 30s
      retries: 3

  seed:
    image: nam-master-backend
    command: /usr/local/bin/entrypoint.sh sh -c "cat ./wait-for-it.sh | sh -s db && python -u -m app.db.seed"
    env_file:
      - .env
    environment:
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_DB=${POSTGRES_DB}
      - ALEMBIC_DATABASE_URL=postgresql://${POSTGRES_USER}:${POSTGRES_PASSWORD}@db:5432/${POSTGRES_DB}
    depends_on:
      db:
        condition: service_healthy
      backend:
        condition: service_healthy

volumes:
  postgres_data:
  uploaded_files:
