import uuid
from sqlalchemy import Column, String, Text, Date, Boolean, JSON, DateTime
from sqlalchemy.dialects.postgresql import UUID
from app.db.base import Base
from sqlalchemy.orm import relationship
from sqlalchemy.sql import func

class School(Base):
    __tablename__ = "schools"
    id = Column(UUID(as_uuid=True), primary_key=True, default=uuid.uuid4)
    name = Column(String(200), nullable=False)
    code = Column(String(20), unique=True, nullable=False)
    address = Column(Text)
    city = Column(String(100))
    state = Column(String(100))
    pincode = Column(String(10))
    contact_phone = Column(String(20))
    contact_email = Column(String(100))
    principal_name = Column(String(100))
    currency = Column(String(10), default="INR")
    established_date = Column(Date)
    settings = Column(JSON, default={})
    is_active = Column(Boolean, default=True)
    is_offline = Column(Boolean, default=False)
    sms_api_key = Column(String(255), nullable=True)
    logo_url = Column(String(500), nullable=True)
    license_expires_at = Column(DateTime(timezone=True), nullable=True)
    license_activated_at = Column(DateTime(timezone=True), nullable=True)
    created_at = Column(DateTime(timezone=True), server_default=func.now())
    updated_at = Column(DateTime(timezone=True), onupdate=func.now())
    users = relationship("User", back_populates="school")
    license_keys = relationship("LicenseKey", back_populates="school")
    classes = relationship("Class", back_populates="school")
    subjects = relationship("Subject", back_populates="school")
    students = relationship("Student", back_populates="school")
    teachers = relationship("Teacher", back_populates="school")
    parents = relationship("Parent", back_populates="school")
    attendance = relationship("Attendance", back_populates="school")
    assessment_types = relationship("AssessmentType", back_populates="school")
    assessments = relationship("Assessment", back_populates="school")
    grades = relationship("Grade", back_populates="school")
    funds = relationship("Fund", back_populates="school")
    fees = relationship("Fee", back_populates="school")
    payments = relationship("Payment", back_populates="school")
    concessions = relationship("Concession", back_populates="school")
    salaries = relationship("Salary", back_populates="school")
    exams = relationship("Exam", back_populates="school")
    exam_series = relationship("ExamSeries", back_populates="school")
    exam_timetables = relationship("ExamTimetable", back_populates="school")
    announcements = relationship("Announcement", back_populates="school")
    books = relationship("Book", back_populates="school")
    book_transactions = relationship("BookTransaction", back_populates="school")
    routes = relationship("Route", back_populates="school")
    student_routes = relationship("StudentRoute", back_populates="school")
    vehicles = relationship("Vehicle", back_populates="school")
    hostels = relationship("Hostel", back_populates="school")
    periods = relationship("Period", back_populates="school")
    timetable_entries = relationship("TimetableEntry", back_populates="school")
    calendar_events = relationship("CalendarEvent", back_populates="school")